routes/web.php
<?php

use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// ~ Resources ~

Route::resource("teachers", TeacherController::class);
Route::resource("subjects", SubjectController::class);

resources/views/crud/profesores/create.blade.php
@extends('layouts.app')

@section('content')
<form action="{{ route('teachers.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="pb-1"><i class="fa-solid fa-chalkboard-user"></i> Nuevo profesor</h1>
                <div class="clearfix">
                    <div class="float-start"><a href="{{route('teachers.index')}}" type="button" class="btn btn-secondary mb-3"><i class="fa-solid fa-arrow-left"></i></a></div>
                    <div class="float-end">
                        <button type="submit" class="btn btn-primary me-1"><i class="fa-solid fa-plus"></i> Crear</button>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-6 d-flex justify-content-center align-items-center mb-5">
                        <div>
                            <p><img src="https://i.ibb.co/Cmp8Xr7/nopic.png"/></p>
                            <p><input type="file" id="inpAvatar" name="avatar" accept="image/png, image/jpeg"></p>
                        </div>
                    </div>
                    <div class="col-md-6 d-flex justify-content-center align-items-center">
                        <div style="font-size: large;">
                            <div class="mb-3">
                                <label for="nombre" class="form-label"><b>Nombre:</b></label>
                                <input type="text" class="form-control" name="nombre">
                                @error('nombre')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="apellidos" class="form-label"><b>Apellidos:</b></label>
                                <input type="text" class="form-control" name="apellidos">
                                @error('apellidos')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="email" class="form-label"><b>Correo electrónico:</b></label>
                                <input type="email" class="form-control" name="email">
                                @error('email')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="asignaturas" class="form-label"><b>Asignaturas:</b></label>
                                @if (count($subjects) > 1)
                                    @foreach ($subjects as $subject)
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="asignaturas[]" value="{{$subject->id}}" id="flexCheckChecked">
                                            <label class="form-check-label" for="flexCheckChecked">
                                            {{$subject->nombre}}
                                            </label>
                                        </div>
                                    @endforeach
                                @else
                                <p><i>No hay asignaturas disponibles.</i></p>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/crud/profesores/edit.blade.php
@extends('layouts.app')

@section('content')
<form action="{{ route('teachers.update', $teacher) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method("PUT")
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="pb-1"><i class="fa-solid fa-chalkboard-user"></i> Editar profesor</h1>
                <div class="clearfix">
                    <div class="float-start"><a href="{{route('teachers.index')}}" type="button" class="btn btn-secondary mb-3"><i class="fa-solid fa-arrow-left"></i></a></div>
                    <div class="float-end">
                        <button type="submit" class="btn btn-primary me-1"><i class="fa-solid fa-floppy-disk"></i> Guardar cambios</button>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-6 d-flex justify-content-center align-items-center mb-5">
                        <div>
                            <p>
                            @if ($teacher->avatar === null)
                                <img width="265px" height="330px" src="https://i.ibb.co/Cmp8Xr7/nopic.png"/>
                            @else
                                <img width="265px" height="330px" src="{{ Storage::url($teacher->avatar) }}" style="object-fit: cover;"/>
                            @endif
                            </p>
                            <p><input type="file" id="inpAvatar" name="avatar" accept="image/png, image/jpeg"></p>
                        </div>
                    </div>
                    <div class="col-md-6 d-flex justify-content-center align-items-center">
                        <div style="font-size: large;">
                            <div class="mb-3">
                                <label for="nombre" class="form-label">Nombre:</label>
                                <input type="text" class="form-control" name="nombre" value="{{$teacher->nombre}}">
                                @error('nombre')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="apellidos" class="form-label">Apellidos:</label>
                                <input type="text" class="form-control" name="apellidos" value="{{$teacher->apellidos}}">
                                @error('apellidos')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="email" class="form-label">Correo electrónico:</label>
                                <input type="email" class="form-control" name="email" value="{{$teacher->email}}">
                                @error('correo')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/crud/profesores/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="pb-1"><i class="fa-solid fa-chalkboard-user"></i> Profesores ({{ count($totalProfesores) }})</h1>
                <div class="clearfix">
                    <div class="float-start"><a href="{{route('teachers.create')}}" type="button" class="btn btn-primary mb-3"><i class="fa-solid fa-plus"></i> Nuevo</a></div>
                    <div class="float-end"><a href="{{route('subjects.index')}}" type="button" class="btn btn-warning"><i class="fa-solid fa-book-open"></i> Asignaturas</a></div>
                </div>
                @if (session('mensaje'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('mensaje') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
                <div class="table-responsive">
                <table class="table rounded-3 overflow-hidden align-middle text-center">
                    <thead>
                        <tr class="table-dark">
                            <th scope="col"></th>
                            <th scope="col">ID</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellidos</th>
                            <th scope="col">Correo electrónico</th>
                            <th scope="col">Asignaturas</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($profesores as $profesor)
                            @php $asignaturasProfesor = App\Models\Subject::where('profesor_id',$profesor->id)->get();@endphp
                            <tr @if (sizeOf($asignaturasProfesor) - 1 < 0) class="table-danger" @else class="table-success" @endif>
                                <th><a href="{{route('teachers.show', $profesor)}}" class="btn btn-success"><i class="fa-solid fa-info"></i></a></th>
                                <th scope="row">{{ $profesor->id }}</th>
                                <td>{{ $profesor->nombre }}</td>
                                <td>{{ $profesor->apellidos }}</td>
                                <td>{{ $profesor->email }}</td>
                                <td>
                                    @foreach ($asignaturasProfesor as $key => $asignatura)
                                        @if ($key < sizeOf($asignaturasProfesor) - 1)
                                            {{ $asignatura->nombre }},
                                        @else
                                            {{ $asignatura->nombre }}
                                        @endif
                                    @endforeach
                                </td>
                                <td>
                                    <a href="{{route('teachers.edit', $profesor)}}" type="button" class="btn btn-warning"><i class="fa-solid fa-pen-to-square"></i></a>
                                    <form id="formBorrar{{$profesor->id}}" class="d-inline" action="{{route('teachers.destroy', $profesor)}}" method="POST">
                                        @csrf
                                        @method("DELETE")
                                        <button type="submit" class="btn btn-danger d-none"><i class="fas fa-trash"></i></button>
                                    </form>
                                    <button class="btn btn-danger" onclick=
                                    "Swal.fire({
                                        title: '¿Desea eliminar al profesor \u201C{{$profesor->nombre}}\u201D?',
                                        showConfirmButton: true,
                                        showCancelButton: true,
                                        confirmButtonText: 'Eliminar',
                                        cancelButtonText: `Cancelar`,
                                        }).then((result) => {
                                        if (result.isConfirmed) {
                                            document.getElementById('formBorrar{{$profesor->id}}').submit();
                                        }
                                    })"
                                    ><i class="fas fa-trash"></i></button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                </div>
                <div class="d-flex">
                    {!! $profesores->links() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/crud/profesores/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="pb-1"><i class="fa-solid fa-chalkboard-user"></i> Detalles del profesor</h1>
                <div class="clearfix">
                    <div class="float-start"><a href="{{route('teachers.index')}}" type="button" class="btn btn-secondary mb-3"><i class="fa-solid fa-arrow-left"></i></a></div>
                    <div class="float-end">
                        <a href="{{route('teachers.edit', $teacher)}}" class="btn btn-warning me-1"><i class="fa-solid fa-pen-to-square"></i> Editar</a>
                        <form id="formBorrar" class="d-inline" action="{{route('teachers.destroy', $teacher)}}" method="POST">
                            @csrf
                            @method("DELETE")
                            <button type="submit" class="btn btn-danger d-none"><i class="fas fa-trash"></i></button>
                        </form>
                            <button class="btn btn-danger" onclick=
                            "Swal.fire({
                                title: '¿Desea eliminar al profesor \u201C{{$teacher->nombre}}\u201D?',
                                showConfirmButton: true,
                                showCancelButton: true,
                                confirmButtonText: 'Eliminar',
                                cancelButtonText: `Cancelar`,
                                }).then((result) => {
                                if (result.isConfirmed) {
                                    document.getElementById('formBorrar').submit();
                                }
                            })"
                            ><i class="fas fa-trash"></i> Eliminar</button>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-6 d-flex justify-content-center align-items-center mb-5">
                        <div>
                            @if ($teacher->avatar === null)
                                <img width="265px" height="330px" src="https://i.ibb.co/Cmp8Xr7/nopic.png"/>
                            @else
                                <img width="265px" height="330px" src="{{ Storage::url($teacher->avatar) }}" style="object-fit: cover;"/>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-6 d-flex justify-content-center align-items-center">
                        <div style="font-size: large;">
                            <p><b>Nombre:</b> {{$teacher->nombre}}</p>
                            <p><b>Apellidos:</b> {{$teacher->apellidos}}</p>
                            <p><b>Correo electrónico:</b> {{$teacher->email}}</p>
                            <p><b>Asignatura/s:</b> @foreach ($subjects as $key => $subject)@if ($key < sizeOf($subjects) - 1){{$subject->nombre}}, @else {{$subject->nombre}} @endif @endforeach</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection