routes/web.php
<?php

use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// ~ Resources ~

Route::resource("teachers", TeacherController::class);
Route::resource("subjects", SubjectController::class);

resources/views/crud/asignaturas/create.blade.php
@extends('layouts.app')

@section('content')
<form action="{{ route('subjects.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="pb-1"><i class="fa-solid fa-chalkboard-user"></i> Nueva asignatura</h1>
                <div class="clearfix">
                    <div class="float-start"><a href="{{route('subjects.index')}}" type="button" class="btn btn-secondary mb-3"><i class="fa-solid fa-arrow-left"></i></a></div>
                    <div class="float-end">
                        <button type="submit" class="btn btn-primary me-1"><i class="fa-solid fa-plus"></i> Crear</button>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-12 d-flex justify-content-center align-items-center">
                        <div style="font-size: large;">
                            <div class="mb-3">
                                <label for="nombre" class="form-label"><b>Nombre:</b></label>
                                <input type="text" class="form-control" name="nombre">
                                @error('nombre')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="profesor" class="form-label"><b>Profesor:</b></label>
                                <select id="profesor" name="profesor" class="form-select" aria-label="Default select example">
                                    <option selected="true" value="">Sin profesor</option>
                                    @foreach ($teachers as $teacher)
                                        <option value="{{ $teacher->id }}">{{ $teacher->nombre }}</option>
                                    @endforeach
                                </select>
                                @error('profesor')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/crud/asignaturas/edit.blade.php
@extends('layouts.app')

@section('content')
<form action="{{ route('subjects.update', $subject) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method("PUT")
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="pb-1"><i class="fa-solid fa-chalkboard-user"></i> Editar asignatura</h1>
                <div class="clearfix">
                    <div class="float-start"><a href="{{route('subjects.index')}}" type="button" class="btn btn-secondary mb-3"><i class="fa-solid fa-arrow-left"></i></a></div>
                    <div class="float-end">
                        <button type="submit" class="btn btn-primary me-1"><i class="fa-solid fa-floppy-disk"></i> Guardar cambios</button>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-12 d-flex justify-content-center align-items-center">
                        <div style="font-size: large;">
                            <div class="mb-3">
                                <label for="nombre" class="form-label">Nombre:</label>
                                <input type="text" class="form-control" name="nombre" value="{{$subject->nombre}}">
                                @error('nombre')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="profesor" class="form-label"><b>Profesor:</b></label>
                                <select id="profesor" name="profesor" class="form-select" aria-label="Default select example">
                                    <option selected="true" value="">Sin profesor</option>
                                    @foreach ($teachers as $teacher)
                                        <option value="{{ $teacher->id }}" @if($teacher->id==$subject->profesor_id) selected @endif>{{ $teacher->nombre }}</option>
                                    @endforeach
                                </select>
                                @error('profesor')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/crud/asignaturas/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('mensaje'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('mensaje') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
                <h1 class="pb-1"><i class="fa-solid fa-book-open"></i> Asignaturas ({{ count($totalAsignaturas) }})</h1>
                <div class="clearfix">
                <div class="float-start"><a href="{{route('subjects.create')}}" type="button" class="btn btn-primary mb-3"><i class="fa-solid fa-plus"></i> Nuevo</a></div>
                <div class="float-end"><a href="{{route('teachers.index')}}" type="button" class="btn btn-success"><i class="fa-solid fa-chalkboard-user"></i> Profesores</a></div>
                </div>
                <div class="table-responsive">
                    <table class="table rounded-3 overflow-hidden align-middle text-center">
                        <thead>
                            <tr class="table-dark">
                                <th scope="col"></th>
                                <th scope="col">ID</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Profesor</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($asignaturas as $asignatura)
                                <tr @if ($asignatura->profesor_id === null) class="table-danger" @else class="table-warning" @endif>
                                    <th><a href="{{route('subjects.show', $asignatura)}}" class="btn btn-success"><i class="fa-solid fa-info"></i></a></th>
                                    <th scope="row">{{ $asignatura->id }}</th>
                                    <td>{{ $asignatura->nombre }}</td>
                                    <td>@if ($asignatura->profesor_id === null) @else {{ $asignatura->teacher->nombre }}@endif</td>
                                    <td>
                                        <a href="{{route('subjects.edit', $asignatura)}}" type="button" class="btn btn-warning"><i class="fa-solid fa-pen-to-square"></i></a>
                                        <form id="formBorrar{{$asignatura->id}}" class="d-inline" action="{{route('subjects.destroy', $asignatura)}}" method="POST">
                                            @csrf
                                            @method("DELETE")
                                            <button type="submit" class="btn btn-danger d-none"><i class="fas fa-trash"></i></button>
                                        </form>
                                        <button class="btn btn-danger" onclick=
                                        "Swal.fire({
                                            title: '¿Desea eliminar la asignatura \u201C{{$asignatura->nombre}}\u201D?',
                                            showConfirmButton: true,
                                            showCancelButton: true,
                                            confirmButtonText: 'Eliminar',
                                            cancelButtonText: `Cancelar`,
                                            }).then((result) => {
                                            if (result.isConfirmed) {
                                                document.getElementById('formBorrar{{$asignatura->id}}').submit();
                                            }
                                        })"
                                        ><i class="fas fa-trash"></i></button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    </div>
                <div class="d-flex">
                    {!! $asignaturas->links() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/crud/asignaturas/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="pb-1"><i class="fa-solid fa-chalkboard-user"></i> Detalles del profesor</h1>
                <div class="clearfix">
                    <div class="float-start"><a href="{{route('subjects.index')}}" type="button" class="btn btn-secondary mb-3"><i class="fa-solid fa-arrow-left"></i></a></div>
                    <div class="float-end">
                        <a href="{{route('subjects.edit', $subject)}}" class="btn btn-warning me-1"><i class="fa-solid fa-pen-to-square"></i> Editar</a>
                        <form id="formBorrar" class="d-inline" action="{{route('subjects.destroy', $subject)}}" method="POST">
                            @csrf
                            @method("DELETE")
                            <button type="submit" class="btn btn-danger d-none"><i class="fas fa-trash"></i></button>
                        </form>
                            <button class="btn btn-danger" onclick=
                            "Swal.fire({
                                title: '¿Desea eliminar la asignatura \u201C{{$subject->nombre}}\u201D?',
                                showConfirmButton: true,
                                showCancelButton: true,
                                confirmButtonText: 'Eliminar',
                                cancelButtonText: `Cancelar`,
                                }).then((result) => {
                                if (result.isConfirmed) {
                                    document.getElementById('formBorrar').submit();
                                }
                            })"
                            ><i class="fas fa-trash"></i> Eliminar</button>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-6 d-flex justify-content-center align-items-center mb-5">
                        <div>
                            @if (!empty($subject->profesor_id))
                                @if ($subject->teacher->avatar === null)
                                    <img width="265px" height="330px" src="https://i.ibb.co/Cmp8Xr7/nopic.png"/>
                                @else
                                    <img width="265px" height="330px" src="{{ Storage::url($subject->teacher->avatar) }}" style="object-fit: cover;"/>
                                @endif
                            @else
                                <img width="265px" height="330px" src="https://i.ibb.co/Cmp8Xr7/nopic.png"/>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-6 d-flex justify-content-center align-items-center">
                        <div style="font-size: large;">
                            <p><b>Nombre:</b> {{$subject->nombre}}</p>
                            <p><b>Profesor:</b>@if (empty($subject->profesor_id)) @else {{$subject->teacher->nombre}} @endif</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection